In [1]:
import pandas as pd

In [2]:
df_laptops = pd.read_csv('laptop_price.csv' , encoding='latin1')

In [3]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 1. Create a Conditional Column from More than 2 choices": np.select()

In [4]:
import numpy as np

In [5]:
# create an array based on multiple price tiers (+2 choices)

# create "conditions" and "values" variables
conditions = [
    df_laptops['Price_euros']>3000,
    (df_laptops['Price_euros']>2000) & (df_laptops['Price_euros']<=3000),
    (df_laptops['Price_euros']>800) & (df_laptops['Price_euros']<=2000),
    df_laptops['Price_euros']<=800
]

values = ['Too Expensive','Expensive','Affordable','Cheap']

In [6]:
# set it to a new column
df_laptops['Price_tiers'] = np.select(conditions,values,default='Unknown')

In [7]:
# show dataframe
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Affordable
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Affordable
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Cheap
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Affordable
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Cheap

In [8]:
# count values inside ""Price_tier" column
df_laptops['Price_tiers'].value_counts()

Price_tiers
Affordable       655
Cheap            511
Expensive        118
Too Expensive     19
Name: count, dtype: int64

# 2 Exercise

In [9]:
# create an array baes on multiple screen size tiers (+2 choices)
# Too Big>16 , Big>14 , Small>12 , Too Small<12

# create ""conditions" and "values" variables
conditions = [
    df_laptops['Inches'] > 16,
    (df_laptops['Inches'] > 14) & (df_laptops['Inches'] <= 16),
    (df_laptops['Inches'] > 12) & (df_laptops['Inches'] <= 14),
    df_laptops['Inches'] <= 12,
]

values = ['Too Big' , 'Big' , 'Small' , 'Too Small']

In [10]:
# set it to a new column
df_laptops['Screen_size'] = np.select(conditions , values,default='Unknown')

In [11]:
# show dataframe
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers,Screen_size
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Affordable,Small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Affordable,Small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Big
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Big
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Affordable,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Cheap,Small
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Affordable,Small
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap,Small
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Big
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Cheap,Big

In [12]:
# count values inside "scree_size" column
df_laptops['Screen_size'].value_counts()

Screen_size
Big          674
Small        419
Too Big      166
Too Small     44
Name: count, dtype: int64

# 3.1. isin(): Single Filtering

In [13]:
# select Apple or HP laptops
df_laptops['Company'].isin(['Apple','HP'])

0        True
1        True
2        True
3        True
4        True
        ...
1298    False
1299    False
1300    False
1301     True
1302    False
Name: Company, Length: 1303, dtype: bool

In [14]:
# filter dataframes
df_laptops[df_laptops['Company'].isin(['Apple','HP'])].value_counts('Company')

Company
HP       274
Apple     21
Name: count, dtype: int64

# 3.2. isin():Multiple Filtering

In [15]:
# find notebooks or ultrabooks form Apple or HP
filter1 = df_laptops['TypeName'].isin(['Notebook','Ultrabook'])
filter2 = df_laptops['Company'].isin(['Apple','HP'])

In [16]:
# filter dataframe
df_laptops[filter1 & filter2]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers,Screen_size
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Affordable,Small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Affordable,Small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Big
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Big
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Affordable,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1273,1291,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Big
1280,1298,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap,Big
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Big
1294,1312,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap,Big
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Big

# 4.Find Duplicate Rows with the .duplicate() Method

# 1.duplicated()

# 4.1. Example 1

In [17]:
# find duplicates in 1 column/series
df_laptops.duplicated('laptop_ID')

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [18]:
# sshow elements in dataframe with duplicates in column 'laptop_ID'
df_laptops[df_laptops.duplicated('laptop_ID')]

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros, Price_tiers, Screen_size]
Index: []

In [19]:
# duplicates in 2 or more columns
df_laptops.duplicated(['Product','TypeName','Inches'])

0       False
1       False
2       False
3       False
4        True
        ...
1298     True
1299     True
1300     True
1301     True
1302     True
Length: 1303, dtype: bool

In [20]:
duplicated = df_laptops.duplicated(['Product','TypeName','Inches'])

In [21]:
# show all the values duplicated (except for the first - keep='first')
df_laptops[duplicated].sort_values(['Product','TypeName'])

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers,Screen_size
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0,Cheap,Big
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0,Cheap,Big
1098,1113,HP,250 G5,Notebook,15.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,1TB HDD,Intel HD Graphics 405,Windows 10,1.96kg,500.0,Cheap,Big
1170,1188,HP,250 G5,Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.96kg,679.0,Cheap,Big
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.9,Cheap,Big
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg,928.0,Affordable,Small
826,835,Asus,ZenBook Flip,2 in 1 Convertible,13.3,Touchscreen / Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1358.0,Affordable,Small
1275,1293,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0,Cheap,Small
1289,1307,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0,Cheap,Small
676,684,Asus,Zenbook 3,Ultrabook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1135.0,Affordable,Small

# 5. Example

##### Task: Find the cheapest and most expensive laptop of each company using the sort_values() and duplicated() methods(keep "first" , "last" and false)

In [22]:
# sort dataframe ascending by company and price
# cheapest first and most expensive last
df_laptops = df_laptops.sort_values(['Company','Price_euros'])
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tiers,Screen_size
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.00,Cheap,Too Small
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,199.00,Cheap,Big
1102,1117,Acer,Chromebook 15,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,4GB,16GB SSD,Intel HD Graphics,Chrome OS,2.20kg,209.00,Cheap,Big
695,703,Acer,TravelMate B117-M,Netbook,11.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.00,Cheap,Too Small
1198,1216,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.00,Cheap,Big
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,195,Vero,K147 (N3350/4GB/32GB/FHD/W10),Notebook,14.0,IPS Panel Full HD 1920x1080,Intel Celeron Dual Core N3350 1.1GHz,4GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.3kg,260.00,Cheap,Small
877,888,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00,Affordable,Small
192,196,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90,Affordable,Small
184,188,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00,Affordable,Big
514,521,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95,Affordable,Big

In [23]:
# check all value categories in "Company" column
df_laptops.value_counts('Company')

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
LG             3
Google         3
Huawei         2
Name: count, dtype: int64

In [24]:
# duplicated values in "Company" columns (default-> keep="first")
duplicated_first = df_laptops.duplicated('Company',keep='first')

In [37]:
# show dataframe with duplicated values in "Company" column
df_laptops[duplicated_first]


# keep='first' (cheapest laptop per company)
# show dataframe with non duplicated values in "Company" column
df_laptops[~duplicated_first][['Company', 'Price_euros']]

# check all value categories
df_laptops[~duplicated_first].value_counts('Company')

Company
Acer         1
Apple        1
Asus         1
Chuwi        1
Dell         1
Fujitsu      1
Google       1
HP           1
Huawei       1
LG           1
Lenovo       1
MSI          1
Mediacom     1
Microsoft    1
Razer        1
Samsung      1
Toshiba      1
Vero         1
Xiaomi       1
Name: count, dtype: int64

In [43]:
# keep='last'
duplicated_last = df_laptops.duplicated('Company',keep='last')
# keep=False
duplicated_false = df_laptops.duplicated('Company',keep=False)

In [44]:
# keep='last' (most expensive laptop per company)
# show dataframe with non duplicated values in "Company" column
df_laptops[~duplicated_last][['Company','Price_euros']]

        Company  Price_euros
1189       Acer      2599.00
17        Apple      2858.00
1066       Asus      3975.00
421       Chuwi       449.00
723        Dell      3659.40
623     Fujitsu       799.00
437      Google      2199.00
749          HP      4389.00
214      Huawei      1499.00
678          LG      2299.00
610      Lenovo      4899.00
177         MSI      2799.00
580    Mediacom       389.00
449   Microsoft      2589.00
196       Razer      6099.00
874     Samsung      1849.00
491     Toshiba      2799.00
191        Vero       260.00
514      Xiaomi      1399.95

In [45]:
# keep=False
# show dataframe with non duplicated values in "Comapny" column
df_laptops[~duplicated_false]

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros, Price_tiers, Screen_size]
Index: []

In [46]:
# all elements in company column are repeated at least once 
df_laptops.value_counts('Company')

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
LG             3
Google         3
Huawei         2
Name: count, dtype: int64

In [51]:
import pandas as pd

In [52]:
df_laptops = pd.read_csv('laptop_price.csv' , encoding='latin1')

In [53]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 6.Duplicate elemets with the .drop_duplicates() Method

# 6.1) drop_duplicates()

In [56]:
# drop duplicates in 2 or more columns
df_laptops.drop_duplicates(['Company'])[['Company','Price_euros']]

       Company  Price_euros
0        Apple      1339.69
2           HP       575.00
5         Acer       400.00
8         Asus      1495.00
13        Dell       498.90
18      Lenovo       499.00
30       Chuwi       244.99
58         MSI      2449.00
70   Microsoft      1089.00
143    Toshiba       602.00
170     Huawei      1349.00
184     Xiaomi      1199.00
191       Vero       260.00
196      Razer      6099.00
429   Mediacom       299.00
430    Samsung       269.00
437     Google      2199.00
567    Fujitsu       739.00
678         LG      2299.00

In [58]:
# sort dataframe ascending by comany and price
# cheapest first and most expensive last
df_laptops = df_laptops.sort_values(['Company','Price_euros'])

In [60]:
# cheapest : keep='first'
df_laptops.drop_duplicates(['Company'],keep='first')[['Company','Price_euros']]

        Company  Price_euros
1215       Acer       174.00
1         Apple       898.94
20         Asus       191.90
30        Chuwi       244.99
340        Dell       274.90
983     Fujitsu       649.00
472      Google      1275.00
1268         HP       209.00
170      Huawei      1349.00
909          LG      1899.00
1272     Lenovo       229.00
1169        MSI       839.00
626    Mediacom       239.00
457   Microsoft       989.00
1117      Razer      1029.00
430     Samsung       269.00
159     Toshiba       447.00
1120       Vero       196.00
877      Xiaomi       935.00

In [65]:
# most expensive: keep='last'
df_laptops.drop_duplicates(['Company'], keep='last', inplace=True, ignore_index=True)

In [66]:
# Arguments

# inplace: drop duplicates in place or to return a copy
# ignore_index=True: the resulting axis will be labeled 0,1,2,..
df_laptops[['Company','Price_euros']]

      Company  Price_euros
0        Acer      2599.00
1       Apple      2858.00
2        Asus      3975.00
3       Chuwi       449.00
4        Dell      3659.40
5     Fujitsu       799.00
6      Google      2199.00
7          HP      4389.00
8      Huawei      1499.00
9          LG      2299.00
10     Lenovo      4899.00
11        MSI      2799.00
12   Mediacom       389.00
13  Microsoft      2589.00
14      Razer      6099.00
15    Samsung      1849.00
16    Toshiba      2799.00
17       Vero       260.00
18     Xiaomi      1399.95

# 7. Exercise 1

Task: Find the biggest and smallest screen size in laptops of each company using the sort_values() and duplicated() methods (keep "first","last" and False

In [69]:
df_laptops = pd.read_csv('laptop_price.csv' , encoding='latin1')

In [70]:
# sort dataframe ascneding by comapany and inches
# smallest first and biggest last
df_laptops = df_laptops.sort_values(['Company','Inches'])

In [72]:
# smallest: keep='first'
df_laptops.drop_duplicates(['Company'], keep='first')[['Company','Inches']]

        Company  Inches
319        Acer    11.6
1234      Apple    11.6
20         Asus    11.6
421       Chuwi    12.3
455        Dell    11.6
567     Fujitsu    15.6
437      Google    12.3
677          HP    11.6
170      Huawei    13.0
909          LG    14.0
50       Lenovo    10.1
785         MSI    14.0
429    Mediacom    11.6
70    Microsoft    13.5
816       Razer    12.5
430     Samsung    11.6
963     Toshiba    12.5
1120       Vero    13.3
192      Xiaomi    13.3

In [74]:
# largest: keep='last'
df_laptops.drop_duplicates(['Company'], keep='last')[['Company','Inches']]

        Company  Inches
1216       Acer    17.3
17        Apple    15.4
1256       Asus    17.3
483       Chuwi    15.6
1243       Dell    17.3
983     Fujitsu    15.6
762      Google    12.3
1136         HP    17.3
214      Huawei    13.0
905          LG    15.6
1217     Lenovo    17.3
177         MSI    18.4
718    Mediacom    14.0
670   Microsoft    13.5
830       Razer    17.3
593     Samsung    15.6
1042    Toshiba    15.6
1041       Vero    14.0
514      Xiaomi    15.6